### ISSUE TITLE
Input size,type and ROS version

### ISSUE THREAD

**Issue by sooosh** [fabvio/ld-lsi#2]
Thank you for a great code to share.
I want to ask you a input resolution and format and ROS version

1.As for the input size
As I read your paper and it says you tested bbd dataset
so I publish 1280HD jpg to cnn_node
I tested using imshow at cnn_node and I successfully show image before converting to torch tensor 
https://github.com/fabvio/ld-lsi/blob/066e5e50648220f76ca9c6a589c450b79202c085/scripts/cnn_node.py#L47
but the following erorr occurs. So I want to know the correct input size or input format.
  
[ERROR] [1564474751.061718]: Cannot obtain output. Exception: size mismatch, m1: [1 x 30720], m2: [7680 x 1024] at /opt/conda/conda-bld/pytorch_1535488076166/work/aten/src/THC/generic/THCTensorMathBlas.cu:249
[ERROR] [1564474751.062359]: Cannot publish message. Exception: local variable 'ego_lane_points' referenced before assignment
[ERROR] [1564474751.063066]: Visualization error. Exception: local variable 'output' referenced before assignment

2.It's compatible with lunar version but I want to use kinetic ver so is it possible to use this in kinetic version and if it's easy change please tell me .

Thank you very much

**Comment by fabvio** [comment]
Hi! I'm going to answer in separate points.

1. Are you sure you are passing to the node images resized in the correct resolution? During inference, images of resolution 640x360 are required. In my opinion, your error code is related to a size mismatch in the linear layers.

2. The code has been programmed in Lunar because in our lab we had everything already on Lunar, but I expect that moving to Kinetik won't be much of an issue. Obviously, I may be wrong :) you can try it and see how it goes, contributions are always very welcome.

**Comment by sooosh** [comment]
Thank you for your answer
1 I  resized picture to 640*360 and then,I managed to run the code using picture mentioned here
https://github.com/fabvio/ld-lsi/issues/1#issue-444299426

I got following result
![Screenshot from 2019-07-31 11-51-55](https://user-images.githubusercontent.com/53468604/62181271-c1852580-b38d-11e9-9b6c-a9234cbf5c96.png)

I assume this is a bit worse. I didnt change anython except resizing to 640*360 before 
Line 47  input_tensor = torch.from_numpy(image) 
Do you have any idea how to fix this problem?

2. Yes I am trying to use  kinetic too then I will tell you if it goes well.

Thank you.

**Comment by fabvio** [comment]
Hi, the output of the CNN in my opinion is correct. In the issue you mentioned, the version of the network without scene inference was being used. Instead, you are using the multi-task one. As it is listed on the paper, the multi-task results were slightly worse, but in our view this is an acceptable compromise since we have also the scene classification branch, that can be used to perform more informed decisions. I expected better results though, also because in the paper there is an experiment with unseen scenes taken in Madrid and the network appears to be kinda robust to the domain shift. I suppose this may be an unique case, or in the input image we have some kind of domain shift that influences more the multi-task network. This is one of the problems in domain adaptation :)

As regards the post-processing output, I suggest you to tune the clustering parameters a little bit, because that one should be definitely better.

Let me know about Kinetik, if you manage to run it you can submit a pull request. Closing the issue for now.

**Comment by fabvio** [comment]
I'm commenting now because now I see the error with the post-processing step, your output is probably downsampled! Try to upsample it and see that it should be a good approximation of the ego lane free space ;)

**Comment by sooosh** [comment]
Thank you for your answer.
Since I am ros beginner I am try solving the conflict with kinetic and lunar though at first.
I am try para tune and single task one too thanks.
